version: '3'

services:
    iobroker:
        restart: always
        build: ./iobroker
        container_name: iobroker-mihome-vacuum
        hostname: iobroker-mihome-vacuum
        # This port is only internal, so we can work on this while another instance of ioBroker is running on the host
        expose:
            - 8081
        volumes:
            - ..:/workspace:cached
            - iobrokerdata-mihome-vacuum:/opt/iobroker
        environment:
            - LANG=en_US.UTF-8
            - LANGUAGE=en_US:en
            - LC_ALL=en_US.UTF-8
            - TZ=Europe/Berlin
            - SETGID=1000

    # Reverse proxy to load up-to-date admin sources from the repo
    nginx:
        image: nginx:latest
        depends_on:
            - iobroker
        links:
            - iobroker
        restart: always
        container_name: nginx-mihome-vacuum
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ..:/workspace:cached
        ports:
            # Make the ioBroker admin available under http://localhost:8082
            - 8082:80

volumes:
    iobrokerdata-mihome-vacuum: